
channels:
  - conda-forge
dependencies:
  - pip: tqdm
  - conda: cctbx=2025.2
optional-dependencies:
  dev:
    - pip: ruff
    - pip: mypy>=1.0,<2.0
    - pip: black[jupyter]>=23.0,<25.0
    - pip: isort>=5.12,<5.14
    - pip: pytest
    - pip: pytest-sphinx
    - pip: pytest-cov
    - pip: twine>=1.11.0
    - pip: build
    - pip: setuptools
    - pip: wheel
    - pip: Sphinx>=6.0,<9.0
    - pip: furo==2024.8.6
    - pip: myst-parser>=1.0
    - pip: sphinx-copybutton
    - pip: sphinx-autobuild
    - pip: sphinx-autodoc-typehints==1.23.3
    - pip: packaging
  sandbox:
    - pip: numpy
    - pip: matplotlib
    - pip: ImageD11
    - pip: ipykernel
    - pip: ipympl
    - pip: tqdm
    - pip: jax[cuda12]
    - cctbx
