
channels:
  - conda-forge
dependencies:
  - pip: tqdm
  - pip: jax
optional_dependencies:
  dev:
    - pip: ruff
    - pip: ty
    - pip: pytest
    - pip: pytest-sphinx
    - pip: pytest-cov
    - pip: ImageD11  # for testing
    - pip: twine
    - pip: build
    - pip: setuptools
    - pip: wheel
    - pip: Sphinx
    - pip: furo
    - pip: myst-parser
    - pip: sphinx-copybutton
    - pip: sphinx-autobuild
    - pip: sphinx-autodoc-typehints
    - pip: sphinx_math_dollar
    - pip: packaging
  sandbox:
    - pip: numpy<2
    - pip: matplotlib
    - pip: ImageD11
    - pip: ipykernel
    - pip: ipympl
    - pip: tqdm
    - pip: jax
#    - pip: silx[full]
#    - conda: cctbx
