
channels:
  - conda-forge
dependencies:
  - pip: tqdm
  - pip: Dans-Diffraction
  - pip: polars
  - pip: jax
  - conda: jax  # [osx]
  # there are more builds for jax on Conda than on pip (better OS/python support)
optional_dependencies:
  cuda12:
    - pip: jax[cuda12]
  cuda13:
    - pip: jax[cuda13]
  dev:
    - pip: ruff
    - pip: ty
    - pip: pytest
    - pip: pytest-sphinx
    - pip: pytest-cov
    - conda: numba  # ImageD11 needs numba, and there are more Numba/llvmlite builds for more platforms on conda than on pip.
    - pip: ImageD11  # for testing
    - pip: twine
    - pip: build
    - pip: setuptools
    - pip: wheel
    - pip: Sphinx
    - pip: pydata-sphinx-theme
    - pip: myst-parser
    - pip: nbsphinx
    - conda: pandoc  # needed for nbsphinx to render notebooks
    - pip: ipython
    - pip: ipykernel  # needed for nbsphinx to render notebooks
    - pip: sphinx-copybutton
    - pip: sphinx-autobuild
    - pip: sphinx-autodoc-typehints
    - pip: sphinx_math_dollar
    - pip: packaging
    - pip: coverage
  sandbox:
    - pip: numpy<2
    - pip: matplotlib
    - pip: ImageD11
    - pip: ipykernel
    - pip: ipympl
    - pip: tqdm
#    - pip: jax
#    - pip: silx[full]
#    - conda: cctbx
