
channels:
  - conda-forge
dependencies:
  - pip: tqdm
  - conda: jax  # [unix]
  # there are more builds for jax on Conda than on pip (better OS/python support)
  - pip: jax    # [win]
  - pip: jaxlib # [win]
  # ^ there are missing jax/jaxlib builds on conda-forge for windows
optional_dependencies:
  dev:
    - pip: ruff
    - pip: ty
    - pip: pytest
    - pip: pytest-sphinx
    - pip: pytest-cov
    - conda: numba  # ImageD11 needs numba, and there are more Numba/llvmlite builds for more platforms on conda than on pip.
    - pip: ImageD11  # for testing
    - pip: twine
    - pip: build
    - pip: setuptools
    - pip: wheel
    - pip: Sphinx
    - pip: pydata-sphinx-theme
    - pip: myst-parser
    - pip: nbsphinx
    - conda: pandoc  # needed for nbsphinx to render notebooks
    - pip: ipykernel  # needed for nbsphinx to render notebooks
    - pip: sphinx-copybutton
    - pip: sphinx-autobuild
    - pip: sphinx-autodoc-typehints
    - pip: sphinx_math_dollar
    - pip: packaging
    - pip: coverage
  sandbox:
    - pip: numpy<2
    - pip: matplotlib
    - pip: ImageD11
    - pip: ipykernel
    - pip: ipympl
    - pip: tqdm
    - pip: jax
#    - pip: silx[full]
#    - conda: cctbx
