name: Conda virtualenv
description: Set up a Python conda virtual environment
inputs:
  python-version:
    description: The Python version to use
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python version we want
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get exact Python version
      id: get-python-version
      run: echo "PYTHON_VERSION=$(python --version | cut -d' ' -f2)" >> $GITHUB_ENV
  
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: anaconda-client-env
        channels: conda-forge, defaults
        auto-update-conda: true
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Install package and dependencies
      run: |
        pip install --upgrade pip unidep
        unidep install .[dev]
    
    - name: Get Conda environment information
      run: |
        conda info
        conda list