name: Python virtualenv
description: Set up a Python conda virtual environment with caching
inputs:
  python-version:
    description: The Python version to use
    required: true
  cache-prefix:
    description: Update this to invalidate the cache
    required: true
    default: v0

runs:
  using: composite
  steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{ inputs.python-version }}

    - shell: bash -l {0}
      run: |
        # Get the exact Python version to use in the cache key.
        echo "PYTHON_VERSION=$(python --version)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      id: virtualenv-cache
      with:
        path: anri_venv
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}

    - if: steps.virtualenv-cache.outputs.cache-hit != 'true'
      shell: bash -l {0}
      run: |
        # Set up virtual environment without cache hit.
        conda create -y --name anri_venv anri python=${{ inputs.python-version }}
        conda activate anri_venv

    - if: steps.virtualenv-cache.outputs.cache-hit == 'true'
      shell: bash -l {0}
      run: |
        conda activate anri_venv
    
    - shell: bash -l {0}
      run: |
        conda info
        conda list